# nixpacks.toml

[phases.setup]
nixPkgs = ['python3', '...']  # 必要なNixパッケージを指定します。'...'を使用して、デフォルトのパッケージに追加します。

[phases.install]
# Flaskとその他の依存関係をインストールするためのコマンドを指定します。
cmds = [
    "pip install -r requirements.txt"
]

[start]
# Flaskアプリケーションを起動するコマンドを指定します。
cmd = "flask run --host=0.0.0.0 --port=${PORT:-5000}"